version: "3.8"
services:
  ubuntu-installer-testing:
    build:
      context: './build'
      dockerfile: ubuntu.dockerfile
    volumes:
      - ./:/usr/pginstaller
    command: ["sleep","infinity"]
    networks:
      - default
  centos-installer-testing:
    build:
      context: './build'
      dockerfile: centos.dockerfile
    volumes:
      - ./:/usr/pginstaller
    command: ["sleep","infinity"]
    networks:
      - default
  fedora-installer-testing:
    build:
      context: './build'
      dockerfile: fedora.dockerfile
    volumes:
      - ./:/usr/pginstaller
    command: ["sleep","infinity"]
    networks:
      - default  
networks:
  default:
    driver: bridge

volumes:
  local: {}
